#! /bin/bash

# Install and source Nix as a cross-platform package manager
curl -L https://nixos.org/nix/install | sh
source ~/.nix-profile/etc/profile.d/nix.sh

# Install packages with Nix
nix-env -iA nixpkgs.git                        
nix-env -iA nixpkgs.gcc                        
nix-env -iA nixpkgs.gnumake                    

nix-env -iA nixpkgs.zsh
nix-env -iA nixpkgs.antibody

nix-env -iA nixpkgs.neovim                     
nix-env -iA nixpkgs.stow                       
nix-env -iA nixpkgs.direnv                     
nix-env -iA nixpkgs.fzf
nix-env -iA nixpkgs.zoxide                     

nix-env -iA nixpkgs.ripgrep                    
nix-env -iA nixpkgs.exa                        
nix-env -iA nixpkgs.du-dust                    
nix-env -iA nixpkgs.fd                         
nix-env -iA nixpkgs.bat                        
nix-env -iA nixpkgs.bottom                     
nix-env -iA nixpkgs.gitui                     
nix-env -iA nixpkgs.difftastic

nix-env -iA nixpkgs.python310                  
nix-env -iA nixpkgs.python310Packages.pip      
nix-env -iA nixpkgs.python310Packages.ipython  
nix-env -iA nixpkgs.python310Packages.ipdb     
nix-env -iA nixpkgs.python310Packages.pynvim   
nix-env -iA nixpkgs.python310Packages.python-lsp-server
nix-env -iA nixpkgs.python310Packages.black
nix-env -iA nixpkgs.python310Packages.flake8
nix-env -iA nixpkgs.python310Packages.mypy
nix-env -iA nixpkgs.python310Packages.isort
nix-env -iA nixpkgs.pipenv

nix-env -iA nixpkgs.sumneko-lua-language-server

nix-env -iA nixpkgs.rustc
nix-env -iA nixpkgs.cargo
nix-env -iA nixpkgs.clippy
nix-env -iA nixpkgs.rust-analyzer
nix-env -iA nixpkgs.rustfmt

# Do some clean-up
nix-collect-garbage

# Set up TPM for tmux
if [[ ! -d $HOME/.tmux ]]
then
    git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
fi

