#! /bin/bash

# Configure zsh as the login shell
command -v zsh | sudo tee -a /etc/shells
sudo chsh -s $(which zsh) $USER

# Bundle plugins
antibody bundle < $HOME/.config/plugins.zsh.txt > $HOME/.config/plugins.zsh
