name: Sanity Check

on:
  push:
    branches: [ "main" ]

jobs:
  scripts:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run backup and setup scripts
        run: |
          ./backup_system.sh
          ./setup_system.sh
